#!/usr/bin/env python3
'''
Plausible Deniabity Toolkit

Mount hidden volumes listed in the configuration file,
then wait when the user presses ENTER key and unmount.

Example:

    pdt_mount config-dir [remote-hostname]

Where `config-dir` is a directory containing `config.json` file

Copyright 2022 amateur80lvl
License: BSD, see LICENSE for details.
'''

import sys

from pdt_base import read_config, procedure, Invoke
from pdt_tasks import MountVolumes, TeardownPressEnter

config_dir = sys.argv[1]
remote = sys.argv[2] if len(sys.argv) > 2 else None
config = read_config(config_dir)
invoke = Invoke(remote=remote)
invoke.set_devices(config)

procedure(
    config, invoke,

    MountVolumes,
    TeardownPressEnter
)
